/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Bush.glb --transform --name Bush -o /Users/christopherneale/projects/fps/src/assets/nature/bush 
Files: /Users/christopherneale/projects/models/nature/Bush.glb [164.71KB] > /Users/christopherneale/projects/fps/src/assets/nature/Bush-transformed.glb [51.27KB] (69%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/bush-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bush_Common.geometry} material={materials.Leaves_TwistedTree} />
    </group>
  )
}

useGLTF.preload('/bush-transformed.glb')
