/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Bush with Flowers.glb --transform --name BushWithFlowers -o /Users/christopherneale/projects/fps/src/assets/nature/bush-with-flowers 
Files: /Users/christopherneale/projects/models/nature/Bush with Flowers.glb [809.73KB] > /Users/christopherneale/projects/fps/src/assets/nature/Bush with Flowers-transformed.glb [176.41KB] (78%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/bush-with-flowers-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bush_Common_Flowers_1.geometry} material={materials.Leaves_NormalTree} />
      <mesh geometry={nodes.Bush_Common_Flowers_2.geometry} material={materials.Flowers} />
    </group>
  )
}

useGLTF.preload('/bush-with-flowers-transformed.glb')
