/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Bush.glb --transform --name Bush -o /Users/christopherneale/projects/fps/src/assets/nature/bush 
Files: /Users/christopherneale/projects/models/nature/Bush.glb [164.71KB] > /Users/christopherneale/projects/fps/src/assets/nature/Bush-transformed.glb [51.27KB] (69%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Bush-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bush_Common.geometry} material={materials.Leaves_TwistedTree} />
    </group>
  )
}

useGLTF.preload('/Bush-transformed.glb')
