/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Bush with Flowers.glb --transform --name BushWithFlowers -o /Users/christopherneale/projects/fps/src/assets/nature/bush-with-flowers 
Files: /Users/christopherneale/projects/models/nature/Bush with Flowers.glb [809.73KB] > /Users/christopherneale/projects/fps/src/assets/nature/Bush with Flowers-transformed.glb [176.41KB] (78%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bush-with-flowers-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bush_Common_Flowers_1.geometry} material={materials.Leaves_NormalTree} />
      <mesh geometry={nodes.Bush_Common_Flowers_2.geometry} material={materials.Flowers} />
    </group>
  )
}

useGLTF.preload('/bush-with-flowers-transformed.glb')
