/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Clover.glb --transform --name Clover -o /Users/christopherneale/projects/fps/src/assets/nature/clover 
Files: /Users/christopherneale/projects/models/nature/Clover.glb [694.43KB] > /Users/christopherneale/projects/fps/src/assets/nature/Clover-transformed.glb [80.83KB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Clover-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Clover_1.geometry} material={materials.Leaves} />
    </group>
  )
}

useGLTF.preload('/Clover-transformed.glb')
