/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Clover-u5SOgBFiut.glb --transform --name CloverU5SOgBFiut -o /Users/christopherneale/projects/fps/src/assets/nature/clover-u5sogbfiut 
Files: /Users/christopherneale/projects/models/nature/Clover-u5SOgBFiut.glb [703.82KB] > /Users/christopherneale/projects/fps/src/assets/nature/Clover-u5SOgBFiut-transformed.glb [82.53KB] (88%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/clover-variant-1-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Clover_2.geometry} material={materials.Leaves} />
    </group>
  )
}

useGLTF.preload('/clover-variant-1-transformed.glb')
