/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Clover-u5SOgBFiut.glb --transform --name CloverU5SOgBFiut -o /Users/christopherneale/projects/fps/src/assets/nature/clover-u5sogbfiut 
Files: /Users/christopherneale/projects/models/nature/Clover-u5SOgBFiut.glb [703.82KB] > /Users/christopherneale/projects/fps/src/assets/nature/Clover-u5SOgBFiut-transformed.glb [82.53KB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Clover-u5SOgBFiut-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Clover_2.geometry} material={materials.Leaves} />
    </group>
  )
}

useGLTF.preload('/Clover-u5SOgBFiut-transformed.glb')
