/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Dead Tree-MlmK5488ou.glb --transform --name DeadTreeMlmK5488ou -o /Users/christopherneale/projects/fps/src/assets/nature/dead-tree-mlmk5488ou 
Files: /Users/christopherneale/projects/models/nature/Dead Tree-MlmK5488ou.glb [2.61MB] > /Users/christopherneale/projects/fps/src/assets/nature/Dead Tree-MlmK5488ou-transformed.glb [160.32KB] (94%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/dead-tree-variant-3-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DeadTree_1.geometry} material={materials.Bark_DeadTree} />
    </group>
  )
}

useGLTF.preload('/dead-tree-variant-3-transformed.glb')
