/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Dead Tree.glb --transform --name DeadTree -o /Users/christopherneale/projects/fps/src/assets/nature/dead-tree 
Files: /Users/christopherneale/projects/models/nature/Dead Tree.glb [2.6MB] > /Users/christopherneale/projects/fps/src/assets/nature/Dead Tree-transformed.glb [158.22KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/dead-tree-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DeadTree_3.geometry} material={materials.Bark_DeadTree} />
    </group>
  )
}

useGLTF.preload('/dead-tree-transformed.glb')
