/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Dead Tree-CD4edbPSGm.glb --transform --name DeadTreeCD4edbPSGm -o /Users/christopherneale/projects/fps/src/assets/nature/dead-tree-cd4edbpsgm 
Files: /Users/christopherneale/projects/models/nature/Dead Tree-CD4edbPSGm.glb [2.6MB] > /Users/christopherneale/projects/fps/src/assets/nature/Dead Tree-CD4edbPSGm-transformed.glb [157.91KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/dead-tree-variant-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DeadTree_5.geometry} material={materials.Bark_DeadTree} />
    </group>
  )
}

useGLTF.preload('/dead-tree-variant-1-transformed.glb')
