/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Dead Tree-n8FhMgMldD.glb --transform --name DeadTreeN8FhMgMldD -o /Users/christopherneale/projects/fps/src/assets/nature/dead-tree-n8fhmgmldd 
Files: /Users/christopherneale/projects/models/nature/Dead Tree-n8FhMgMldD.glb [2.6MB] > /Users/christopherneale/projects/fps/src/assets/nature/Dead Tree-n8FhMgMldD-transformed.glb [158.37KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/dead-tree-variant-4-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DeadTree_4.geometry} material={materials.Bark_DeadTree} />
    </group>
  )
}

useGLTF.preload('/dead-tree-variant-4-transformed.glb')
