/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Dead Tree-MlmK5488ou.glb --transform --name DeadTreeMlmK5488ou -o /Users/christopherneale/projects/fps/src/assets/nature/dead-tree-mlmk5488ou 
Files: /Users/christopherneale/projects/models/nature/Dead Tree-MlmK5488ou.glb [2.61MB] > /Users/christopherneale/projects/fps/src/assets/nature/Dead Tree-MlmK5488ou-transformed.glb [160.32KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Dead Tree-MlmK5488ou-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DeadTree_1.geometry} material={materials.Bark_DeadTree} />
    </group>
  )
}

useGLTF.preload('/Dead Tree-MlmK5488ou-transformed.glb')
