/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Dead Tree.glb --transform --name DeadTree -o /Users/christopherneale/projects/fps/src/assets/nature/dead-tree 
Files: /Users/christopherneale/projects/models/nature/Dead Tree.glb [2.6MB] > /Users/christopherneale/projects/fps/src/assets/nature/Dead Tree-transformed.glb [158.22KB] (94%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/dead-tree-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DeadTree_3.geometry} material={materials.Bark_DeadTree} />
    </group>
  )
}

useGLTF.preload('/dead-tree-transformed.glb')
