/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Dead Tree-Mcd2zYqyww.glb --transform --name DeadTreeMcd2zYqyww -o /Users/christopherneale/projects/fps/src/assets/nature/dead-tree-mcd2zyqyww 
Files: /Users/christopherneale/projects/models/nature/Dead Tree-Mcd2zYqyww.glb [2.62MB] > /Users/christopherneale/projects/fps/src/assets/nature/Dead Tree-Mcd2zYqyww-transformed.glb [161.32KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/dead-tree-variant-2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DeadTree_2.geometry} material={materials.Bark_DeadTree} />
    </group>
  )
}

useGLTF.preload('/dead-tree-variant-2-transformed.glb')
