/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Fern.glb --transform --name Fern -o /Users/christopherneale/projects/fps/src/assets/nature/fern 
Files: /Users/christopherneale/projects/models/nature/Fern.glb [692.72KB] > /Users/christopherneale/projects/fps/src/assets/nature/Fern-transformed.glb [80.83KB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Fern-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Fern_1.geometry} material={materials.Leaves} />
    </group>
  )
}

useGLTF.preload('/Fern-transformed.glb')
