/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Flower Single.glb --transform --name FlowerSingle -o /Users/christopherneale/projects/fps/src/assets/nature/flower-single 
Files: /Users/christopherneale/projects/models/nature/Flower Single.glb [1.22MB] > /Users/christopherneale/projects/fps/src/assets/nature/Flower Single-transformed.glb [153.41KB] (87%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/flower-single-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Flower_3_Single_1.geometry} material={materials.Flowers} />
      <mesh geometry={nodes.Flower_3_Single_2.geometry} material={materials.Leaves} />
    </group>
  )
}

useGLTF.preload('/flower-single-transformed.glb')
