/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Flower Petal.glb --transform --name FlowerPetal -o /Users/christopherneale/projects/fps/src/assets/nature/flower-petal 
Files: /Users/christopherneale/projects/models/nature/Flower Petal.glb [531.67KB] > /Users/christopherneale/projects/fps/src/assets/nature/Flower Petal-transformed.glb [73.41KB] (86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/flower-petal-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Petal_2.geometry} material={materials.Flowers} />
    </group>
  )
}

useGLTF.preload('/flower-petal-transformed.glb')
