/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Flower Group-LqTljN6Wg2.glb --transform --name FlowerGroupLqTljN6Wg2 -o /Users/christopherneale/projects/fps/src/assets/nature/flower-group-lqtljn6wg2 
Files: /Users/christopherneale/projects/models/nature/Flower Group-LqTljN6Wg2.glb [1.28MB] > /Users/christopherneale/projects/fps/src/assets/nature/Flower Group-LqTljN6Wg2-transformed.glb [162.82KB] (87%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/flower-group-variant-1-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Flower_4_Group_1.geometry} material={materials.Leaves} />
      <mesh geometry={nodes.Flower_4_Group_2.geometry} material={materials.Flowers} />
    </group>
  )
}

useGLTF.preload('/flower-group-variant-1-transformed.glb')
