/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Flower Petal-LqvxG9OBOU.glb --transform --name FlowerPetalLqvxG9OBOU -o /Users/christopherneale/projects/fps/src/assets/nature/flower-petal-lqvxg9obou 
Files: /Users/christopherneale/projects/models/nature/Flower Petal-LqvxG9OBOU.glb [531.61KB] > /Users/christopherneale/projects/fps/src/assets/nature/Flower Petal-LqvxG9OBOU-transformed.glb [73.4KB] (86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Flower Petal-LqvxG9OBOU-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Petal_1.geometry} material={materials.Flowers} />
    </group>
  )
}

useGLTF.preload('/Flower Petal-LqvxG9OBOU-transformed.glb')
