/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Flower Petal.glb --transform --name FlowerPetal -o /Users/christopherneale/projects/fps/src/assets/nature/flower-petal 
Files: /Users/christopherneale/projects/models/nature/Flower Petal.glb [531.67KB] > /Users/christopherneale/projects/fps/src/assets/nature/Flower Petal-transformed.glb [73.41KB] (86%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/flower-petal-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Petal_2.geometry} material={materials.Flowers} />
    </group>
  )
}

useGLTF.preload('/flower-petal-transformed.glb')
