/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Flower Petal-eVE0j49ux9.glb --transform --name FlowerPetalEVE0j49ux9 -o /Users/christopherneale/projects/fps/src/assets/nature/flower-petal-eve0j49ux9 
Files: /Users/christopherneale/projects/models/nature/Flower Petal-eVE0j49ux9.glb [531.68KB] > /Users/christopherneale/projects/fps/src/assets/nature/Flower Petal-eVE0j49ux9-transformed.glb [73.43KB] (86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/flower-petal-variant-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Petal_3.geometry} material={materials.Flowers} />
    </group>
  )
}

useGLTF.preload('/flower-petal-variant-1-transformed.glb')
