/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Flower Petal-tzG4JcqYWs.glb --transform --name FlowerPetalTzG4JcqYWs -o /Users/christopherneale/projects/fps/src/assets/nature/flower-petal-tzg4jcqyws 
Files: /Users/christopherneale/projects/models/nature/Flower Petal-tzG4JcqYWs.glb [531.68KB] > /Users/christopherneale/projects/fps/src/assets/nature/Flower Petal-tzG4JcqYWs-transformed.glb [73.43KB] (86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/flower-petal-variant-4-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Petal_5.geometry} material={materials.Flowers} />
    </group>
  )
}

useGLTF.preload('/flower-petal-variant-4-transformed.glb')
