/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Flower Petal-niuBUEJdvM.glb --transform --name FlowerPetalNiuBUEJdvM -o /Users/christopherneale/projects/fps/src/assets/nature/flower-petal-niubuejdvm 
Files: /Users/christopherneale/projects/models/nature/Flower Petal-niuBUEJdvM.glb [532.06KB] > /Users/christopherneale/projects/fps/src/assets/nature/Flower Petal-niuBUEJdvM-transformed.glb [73.52KB] (86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Flower Petal-niuBUEJdvM-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Petal_4.geometry} material={materials.Flowers} />
    </group>
  )
}

useGLTF.preload('/Flower Petal-niuBUEJdvM-transformed.glb')
