/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Flower Single.glb --transform --name FlowerSingle -o /Users/christopherneale/projects/fps/src/assets/nature/flower-single 
Files: /Users/christopherneale/projects/models/nature/Flower Single.glb [1.22MB] > /Users/christopherneale/projects/fps/src/assets/nature/Flower Single-transformed.glb [153.41KB] (87%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Flower Single-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Flower_3_Single_1.geometry} material={materials.Flowers} />
      <mesh geometry={nodes.Flower_3_Single_2.geometry} material={materials.Leaves} />
    </group>
  )
}

useGLTF.preload('/Flower Single-transformed.glb')
