/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Flower Group.glb --transform --name FlowerGroup -o /Users/christopherneale/projects/fps/src/assets/nature/flower-group 
Files: /Users/christopherneale/projects/models/nature/Flower Group.glb [1.24MB] > /Users/christopherneale/projects/fps/src/assets/nature/Flower Group-transformed.glb [156.9KB] (87%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/flower-group-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Flower_3_Group_1.geometry} material={materials.Flowers} />
      <mesh geometry={nodes.Flower_3_Group_2.geometry} material={materials.Leaves} />
    </group>
  )
}

useGLTF.preload('/flower-group-transformed.glb')
