/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Flower Single-GvfHo0roi3.glb --transform --name FlowerSingleGvfHo0roi3 -o /Users/christopherneale/projects/fps/src/assets/nature/flower-single-gvfho0roi3 
Files: /Users/christopherneale/projects/models/nature/Flower Single-GvfHo0roi3.glb [1.24MB] > /Users/christopherneale/projects/fps/src/assets/nature/Flower Single-GvfHo0roi3-transformed.glb [156.08KB] (87%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/flower-single-variant-1-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Flower_4_Single_1.geometry} material={materials.Leaves} />
      <mesh geometry={nodes.Flower_4_Single_2.geometry} material={materials.Flowers} />
    </group>
  )
}

useGLTF.preload('/flower-single-variant-1-transformed.glb')
