/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Grass.glb --transform --name Grass -o /Users/christopherneale/projects/fps/src/assets/nature/grass 
Files: /Users/christopherneale/projects/models/nature/Grass.glb [79.8KB] > /Users/christopherneale/projects/fps/src/assets/nature/Grass-transformed.glb [6.96KB] (91%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/grass-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Grass_Common_Short.geometry} material={materials.Grass} />
    </group>
  )
}

useGLTF.preload('/grass-transformed.glb')
