/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Grass Wispy.glb --transform --name GrassWispy -o /Users/christopherneale/projects/fps/src/assets/nature/grass-wispy 
Files: /Users/christopherneale/projects/models/nature/Grass Wispy.glb [101.41KB] > /Users/christopherneale/projects/fps/src/assets/nature/Grass Wispy-transformed.glb [10.08KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Grass Wispy-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Grass_Wispy_Tall.geometry} material={materials.Grass} />
    </group>
  )
}

useGLTF.preload('/Grass Wispy-transformed.glb')
