/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Grass Wispy-Msr9zx66VU.glb --transform --name GrassWispyMsr9zx66VU -o /Users/christopherneale/projects/fps/src/assets/nature/grass-wispy-msr9zx66vu 
Files: /Users/christopherneale/projects/models/nature/Grass Wispy-Msr9zx66VU.glb [97.19KB] > /Users/christopherneale/projects/fps/src/assets/nature/Grass Wispy-Msr9zx66VU-transformed.glb [9.84KB] (90%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/grass-wispy-variant-1-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Grass_Wispy_Short.geometry} material={materials.Grass} />
    </group>
  )
}

useGLTF.preload('/grass-wispy-variant-1-transformed.glb')
