/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Grass.glb --transform --name Grass -o /Users/christopherneale/projects/fps/src/assets/nature/grass 
Files: /Users/christopherneale/projects/models/nature/Grass.glb [79.8KB] > /Users/christopherneale/projects/fps/src/assets/nature/Grass-transformed.glb [6.96KB] (91%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/grass-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Grass_Common_Short.geometry} material={materials.Grass} />
    </group>
  )
}

useGLTF.preload('/grass-transformed.glb')
