/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Mushroom Laetiporus.glb --transform --name MushroomLaetiporus -o /Users/christopherneale/projects/fps/src/assets/nature/mushroom-laetiporus 
Files: /Users/christopherneale/projects/models/nature/Mushroom Laetiporus.glb [1.26MB] > /Users/christopherneale/projects/fps/src/assets/nature/Mushroom Laetiporus-transformed.glb [103.98KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mushroom-laetiporus-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mushroom_Laetiporus.geometry} material={materials.Mushrooms} />
    </group>
  )
}

useGLTF.preload('/mushroom-laetiporus-transformed.glb')
