/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Mushroom.glb --transform --name Mushroom -o /Users/christopherneale/projects/fps/src/assets/nature/mushroom 
Files: /Users/christopherneale/projects/models/nature/Mushroom.glb [1.21MB] > /Users/christopherneale/projects/fps/src/assets/nature/Mushroom-transformed.glb [94.65KB] (92%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/mushroom-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mushroom_Common.geometry} material={materials.Mushrooms} />
    </group>
  )
}

useGLTF.preload('/mushroom-transformed.glb')
