/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Mushroom.glb --transform --name Mushroom -o /Users/christopherneale/projects/fps/src/assets/nature/mushroom 
Files: /Users/christopherneale/projects/models/nature/Mushroom.glb [1.21MB] > /Users/christopherneale/projects/fps/src/assets/nature/Mushroom-transformed.glb [94.65KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Mushroom-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mushroom_Common.geometry} material={materials.Mushrooms} />
    </group>
  )
}

useGLTF.preload('/Mushroom-transformed.glb')
