/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Pebble Square-s71L3q1nXN.glb --transform --name PebbleSquareS71L3q1nXN -o /Users/christopherneale/projects/fps/src/assets/nature/pebble-square-s71l3q1nxn 
Files: /Users/christopherneale/projects/models/nature/Pebble Square-s71L3q1nXN.glb [814.76KB] > /Users/christopherneale/projects/fps/src/assets/nature/Pebble Square-s71L3q1nXN-transformed.glb [49.74KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pebble-square-variant-5-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pebble_Square_5.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/pebble-square-variant-5-transformed.glb')
