/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Pebble Round-KYtJ6JNXh2.glb --transform --name PebbleRoundKYtJ6JNXh2 -o /Users/christopherneale/projects/fps/src/assets/nature/pebble-round-kytj6jnxh2 
Files: /Users/christopherneale/projects/models/nature/Pebble Round-KYtJ6JNXh2.glb [813.79KB] > /Users/christopherneale/projects/fps/src/assets/nature/Pebble Round-KYtJ6JNXh2-transformed.glb [49.98KB] (94%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/pebble-round-variant-3-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pebble_Round_2.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/pebble-round-variant-3-transformed.glb')
