/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Pebble Square-l5XiYQj1oD.glb --transform --name PebbleSquareL5XiYQj1oD -o /Users/christopherneale/projects/fps/src/assets/nature/pebble-square-l5xiyqj1od 
Files: /Users/christopherneale/projects/models/nature/Pebble Square-l5XiYQj1oD.glb [814.23KB] > /Users/christopherneale/projects/fps/src/assets/nature/Pebble Square-l5XiYQj1oD-transformed.glb [49.68KB] (94%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/pebble-square-variant-3-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pebble_Square_6.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/pebble-square-variant-3-transformed.glb')
