/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Pebble Square-l5XiYQj1oD.glb --transform --name PebbleSquareL5XiYQj1oD -o /Users/christopherneale/projects/fps/src/assets/nature/pebble-square-l5xiyqj1od 
Files: /Users/christopherneale/projects/models/nature/Pebble Square-l5XiYQj1oD.glb [814.23KB] > /Users/christopherneale/projects/fps/src/assets/nature/Pebble Square-l5XiYQj1oD-transformed.glb [49.68KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pebble-square-variant-3-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pebble_Square_6.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/pebble-square-variant-3-transformed.glb')
