/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Pebble Round-nMf8LHOsbM.glb --transform --name PebbleRoundNMf8LHOsbM -o /Users/christopherneale/projects/fps/src/assets/nature/pebble-round-nmf8lhosbm 
Files: /Users/christopherneale/projects/models/nature/Pebble Round-nMf8LHOsbM.glb [815.06KB] > /Users/christopherneale/projects/fps/src/assets/nature/Pebble Round-nMf8LHOsbM-transformed.glb [50.06KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Pebble Round-nMf8LHOsbM-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pebble_Round_5.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/Pebble Round-nMf8LHOsbM-transformed.glb')
