/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Pebble Round-icVsN3lmVy.glb --transform --name PebbleRoundIcVsN3lmVy -o /Users/christopherneale/projects/fps/src/assets/nature/pebble-round-icvsn3lmvy 
Files: /Users/christopherneale/projects/models/nature/Pebble Round-icVsN3lmVy.glb [814.21KB] > /Users/christopherneale/projects/fps/src/assets/nature/Pebble Round-icVsN3lmVy-transformed.glb [50.11KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Pebble Round-icVsN3lmVy-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pebble_Round_1.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/Pebble Round-icVsN3lmVy-transformed.glb')
