/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Pebble Round-kAMfq1uJUY.glb --transform --name PebbleRoundKAMfq1uJUY -o /Users/christopherneale/projects/fps/src/assets/nature/pebble-round-kamfq1ujuy 
Files: /Users/christopherneale/projects/models/nature/Pebble Round-kAMfq1uJUY.glb [814.63KB] > /Users/christopherneale/projects/fps/src/assets/nature/Pebble Round-kAMfq1uJUY-transformed.glb [50.1KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pebble-round-variant-2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pebble_Round_4.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/pebble-round-variant-2-transformed.glb')
