/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Pebble Square.glb --transform --name PebbleSquare -o /Users/christopherneale/projects/fps/src/assets/nature/pebble-square 
Files: /Users/christopherneale/projects/models/nature/Pebble Square.glb [812.94KB] > /Users/christopherneale/projects/fps/src/assets/nature/Pebble Square-transformed.glb [49.57KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Pebble Square-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pebble_Square_4.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/Pebble Square-transformed.glb')
