/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Pebble Round.glb --transform --name PebbleRound -o /Users/christopherneale/projects/fps/src/assets/nature/pebble-round 
Files: /Users/christopherneale/projects/models/nature/Pebble Round.glb [813.87KB] > /Users/christopherneale/projects/fps/src/assets/nature/Pebble Round-transformed.glb [50.04KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pebble-round-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pebble_Round_3.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/pebble-round-transformed.glb')
