/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Pebble Square-Mm4RMgwNO8.glb --transform --name PebbleSquareMm4RMgwNO8 -o /Users/christopherneale/projects/fps/src/assets/nature/pebble-square-mm4rmgwno8 
Files: /Users/christopherneale/projects/models/nature/Pebble Square-Mm4RMgwNO8.glb [815.11KB] > /Users/christopherneale/projects/fps/src/assets/nature/Pebble Square-Mm4RMgwNO8-transformed.glb [49.75KB] (94%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/pebble-square-variant-4-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pebble_Square_2.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/pebble-square-variant-4-transformed.glb')
