/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Pebble Round.glb --transform --name PebbleRound -o /Users/christopherneale/projects/fps/src/assets/nature/pebble-round 
Files: /Users/christopherneale/projects/models/nature/Pebble Round.glb [813.87KB] > /Users/christopherneale/projects/fps/src/assets/nature/Pebble Round-transformed.glb [50.04KB] (94%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/pebble-round-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pebble_Round_3.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/pebble-round-transformed.glb')
