/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Pebble Square-6juX57sLHe.glb --transform --name PebbleSquare6juX57sLHe -o /Users/christopherneale/projects/fps/src/assets/nature/pebble-square-6jux57slhe 
Files: /Users/christopherneale/projects/models/nature/Pebble Square-6juX57sLHe.glb [816.04KB] > /Users/christopherneale/projects/fps/src/assets/nature/Pebble Square-6juX57sLHe-transformed.glb [49.94KB] (94%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/pebble-square-variant-2-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pebble_Square_1.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/pebble-square-variant-2-transformed.glb')
