/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Pine-Zt62gceKXZ.glb --transform --name PineZt62gceKXZ -o /Users/christopherneale/projects/fps/src/assets/nature/pine-zt62gcekxz 
Files: /Users/christopherneale/projects/models/nature/Pine-Zt62gceKXZ.glb [2.22MB] > /Users/christopherneale/projects/fps/src/assets/nature/Pine-Zt62gceKXZ-transformed.glb [138.96KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Pine-Zt62gceKXZ-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pine_2_1.geometry} material={materials.Bark_NormalTree} />
      <mesh geometry={nodes.Pine_2_2.geometry} material={materials.Leaves_Pine} />
    </group>
  )
}

useGLTF.preload('/Pine-Zt62gceKXZ-transformed.glb')
