/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Pine.glb --transform --name Pine -o /Users/christopherneale/projects/fps/src/assets/nature/pine 
Files: /Users/christopherneale/projects/models/nature/Pine.glb [2.15MB] > /Users/christopherneale/projects/fps/src/assets/nature/Pine-transformed.glb [132.09KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Pine-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pine_5_1.geometry} material={materials.Bark_NormalTree} />
      <mesh geometry={nodes.Pine_5_2.geometry} material={materials.Leaves_Pine} />
    </group>
  )
}

useGLTF.preload('/Pine-transformed.glb')
