/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Pine-rfnxJv0Rqa.glb --transform --name PineRfnxJv0Rqa -o /Users/christopherneale/projects/fps/src/assets/nature/pine-rfnxjv0rqa 
Files: /Users/christopherneale/projects/models/nature/Pine-rfnxJv0Rqa.glb [2.23MB] > /Users/christopherneale/projects/fps/src/assets/nature/Pine-rfnxJv0Rqa-transformed.glb [140.06KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Pine-rfnxJv0Rqa-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pine_1_1.geometry} material={materials.Bark_NormalTree} />
      <mesh geometry={nodes.Pine_1_2.geometry} material={materials.Leaves_Pine} />
    </group>
  )
}

useGLTF.preload('/Pine-rfnxJv0Rqa-transformed.glb')
