/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Pine-79gmlLnweB.glb --transform --name Pine79gmlLnweB -o /Users/christopherneale/projects/fps/src/assets/nature/pine-79gmllnweb 
Files: /Users/christopherneale/projects/models/nature/Pine-79gmlLnweB.glb [2.22MB] > /Users/christopherneale/projects/fps/src/assets/nature/Pine-79gmlLnweB-transformed.glb [140.25KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Pine-79gmlLnweB-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pine_4_1.geometry} material={materials.Bark_NormalTree} />
      <mesh geometry={nodes.Pine_4_2.geometry} material={materials.Leaves_Pine} />
    </group>
  )
}

useGLTF.preload('/Pine-79gmlLnweB-transformed.glb')
