/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Pine-79gmlLnweB.glb --transform --name Pine79gmlLnweB -o /Users/christopherneale/projects/fps/src/assets/nature/pine-79gmllnweb 
Files: /Users/christopherneale/projects/models/nature/Pine-79gmlLnweB.glb [2.22MB] > /Users/christopherneale/projects/fps/src/assets/nature/Pine-79gmlLnweB-transformed.glb [140.25KB] (94%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/pine-variant-2-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pine_4_1.geometry} material={materials.Bark_NormalTree} />
      <mesh geometry={nodes.Pine_4_2.geometry} material={materials.Leaves_Pine} />
    </group>
  )
}

useGLTF.preload('/pine-variant-2-transformed.glb')
