/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Pine-699sFuLCN2.glb --transform --name Pine699sFuLCN2 -o /Users/christopherneale/projects/fps/src/assets/nature/pine-699sfulcn2 
Files: /Users/christopherneale/projects/models/nature/Pine-699sFuLCN2.glb [2.26MB] > /Users/christopherneale/projects/fps/src/assets/nature/Pine-699sFuLCN2-transformed.glb [141.8KB] (94%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/pine-variant-1-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pine_3_1.geometry} material={materials.Bark_NormalTree} />
      <mesh geometry={nodes.Pine_3_2.geometry} material={materials.Leaves_Pine} />
    </group>
  )
}

useGLTF.preload('/pine-variant-1-transformed.glb')
