/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Plant.glb --transform --name Plant -o /Users/christopherneale/projects/fps/src/assets/nature/plant 
Files: /Users/christopherneale/projects/models/nature/Plant.glb [685.82KB] > /Users/christopherneale/projects/fps/src/assets/nature/Plant-transformed.glb [79.4KB] (88%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/plant-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plant_1.geometry} material={materials.Leaves} />
    </group>
  )
}

useGLTF.preload('/plant-transformed.glb')
