/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Plant.glb --transform --name Plant -o /Users/christopherneale/projects/fps/src/assets/nature/plant 
Files: /Users/christopherneale/projects/models/nature/Plant.glb [685.82KB] > /Users/christopherneale/projects/fps/src/assets/nature/Plant-transformed.glb [79.4KB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/plant-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plant_1.geometry} material={materials.Leaves} />
    </group>
  )
}

useGLTF.preload('/plant-transformed.glb')
