/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Plant Big.glb --transform --name PlantBig -o /Users/christopherneale/projects/fps/src/assets/nature/plant-big 
Files: /Users/christopherneale/projects/models/nature/Plant Big.glb [683.87KB] > /Users/christopherneale/projects/fps/src/assets/nature/Plant Big-transformed.glb [79.15KB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Plant Big-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plant_7_Big.geometry} material={materials.Leaves} />
    </group>
  )
}

useGLTF.preload('/Plant Big-transformed.glb')
