/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Plant-xH5gNlQxAZ.glb --transform --name PlantXH5gNlQxAZ -o /Users/christopherneale/projects/fps/src/assets/nature/plant-xh5gnlqxaz 
Files: /Users/christopherneale/projects/models/nature/Plant-xH5gNlQxAZ.glb [681.17KB] > /Users/christopherneale/projects/fps/src/assets/nature/Plant-xH5gNlQxAZ-transformed.glb [78.54KB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/plant-variant-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plant_7.geometry} material={materials.Leaves} />
    </group>
  )
}

useGLTF.preload('/plant-variant-1-transformed.glb')
