/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Plant Big-MbhbP7JrTI.glb --transform --name PlantBigMbhbP7JrTI -o /Users/christopherneale/projects/fps/src/assets/nature/plant-big-mbhbp7jrti 
Files: /Users/christopherneale/projects/models/nature/Plant Big-MbhbP7JrTI.glb [698.78KB] > /Users/christopherneale/projects/fps/src/assets/nature/Plant Big-MbhbP7JrTI-transformed.glb [81.72KB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/plant-big-variant-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plant_1_Big.geometry} material={materials.Leaves} />
    </group>
  )
}

useGLTF.preload('/plant-big-variant-1-transformed.glb')
