/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Plant Big-MbhbP7JrTI.glb --transform --name PlantBigMbhbP7JrTI -o /Users/christopherneale/projects/fps/src/assets/nature/plant-big-mbhbp7jrti 
Files: /Users/christopherneale/projects/models/nature/Plant Big-MbhbP7JrTI.glb [698.78KB] > /Users/christopherneale/projects/fps/src/assets/nature/Plant Big-MbhbP7JrTI-transformed.glb [81.72KB] (88%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/plant-big-variant-1-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plant_1_Big.geometry} material={materials.Leaves} />
    </group>
  )
}

useGLTF.preload('/plant-big-variant-1-transformed.glb')
