/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Rock Medium-JQxF95498B.glb --transform --name RockMediumJQxF95498B -o /Users/christopherneale/projects/fps/src/assets/nature/rock-medium-jqxf95498b 
Files: /Users/christopherneale/projects/models/nature/Rock Medium-JQxF95498B.glb [1.07MB] > /Users/christopherneale/projects/fps/src/assets/nature/Rock Medium-JQxF95498B-transformed.glb [56.84KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rock-medium-variant-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock_Medium_3.geometry} material={materials.Rocks} />
    </group>
  )
}

useGLTF.preload('/rock-medium-variant-1-transformed.glb')
