/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Rock Medium-JQxF95498B.glb --transform --name RockMediumJQxF95498B -o /Users/christopherneale/projects/fps/src/assets/nature/rock-medium-jqxf95498b 
Files: /Users/christopherneale/projects/models/nature/Rock Medium-JQxF95498B.glb [1.07MB] > /Users/christopherneale/projects/fps/src/assets/nature/Rock Medium-JQxF95498B-transformed.glb [56.84KB] (95%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/rock-medium-variant-1-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock_Medium_3.geometry} material={materials.Rocks} />
    </group>
  )
}

useGLTF.preload('/rock-medium-variant-1-transformed.glb')
