/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Rock Path Square Smal.glb --transform --name RockPathSquareSmal -o /Users/christopherneale/projects/fps/src/assets/nature/rock-path-square-smal 
Files: /Users/christopherneale/projects/models/nature/Rock Path Square Smal.glb [848.47KB] > /Users/christopherneale/projects/fps/src/assets/nature/Rock Path Square Smal-transformed.glb [53.03KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Rock Path Square Smal-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.RockPath_Square_Small_3.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/Rock Path Square Smal-transformed.glb')
