/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Rock Path Round Small.glb --transform --name RockPathRoundSmall -o /Users/christopherneale/projects/fps/src/assets/nature/rock-path-round-small 
Files: /Users/christopherneale/projects/models/nature/Rock Path Round Small.glb [876.84KB] > /Users/christopherneale/projects/fps/src/assets/nature/Rock Path Round Small-transformed.glb [55.5KB] (94%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/rock-path-round-small-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.RockPath_Round_Small_3.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/rock-path-round-small-transformed.glb')
