/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Rock Path Square Wide.glb --transform --name RockPathSquareWide -o /Users/christopherneale/projects/fps/src/assets/nature/rock-path-square-wide 
Files: /Users/christopherneale/projects/models/nature/Rock Path Square Wide.glb [963.3KB] > /Users/christopherneale/projects/fps/src/assets/nature/Rock Path Square Wide-transformed.glb [64KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Rock Path Square Wide-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.RockPath_Square_Wide.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/Rock Path Square Wide-transformed.glb')
