/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Rock Path Round Thin.glb --transform --name RockPathRoundThin -o /Users/christopherneale/projects/fps/src/assets/nature/rock-path-round-thin 
Files: /Users/christopherneale/projects/models/nature/Rock Path Round Thin.glb [961.04KB] > /Users/christopherneale/projects/fps/src/assets/nature/Rock Path Round Thin-transformed.glb [63.06KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rock-path-round-thin-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.RockPath_Round_Thin.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/rock-path-round-thin-transformed.glb')
