/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Rock Medium.glb --transform --name RockMedium -o /Users/christopherneale/projects/fps/src/assets/nature/rock-medium 
Files: /Users/christopherneale/projects/models/nature/Rock Medium.glb [1.06MB] > /Users/christopherneale/projects/fps/src/assets/nature/Rock Medium-transformed.glb [55.12KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rock-medium-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock_Medium_2.geometry} material={materials.Rocks} />
    </group>
  )
}

useGLTF.preload('/rock-medium-transformed.glb')
