/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Rock Path Square Smal-w4TKZMjjcw.glb --transform --name RockPathSquareSmalW4TKZMjjcw -o /Users/christopherneale/projects/fps/src/assets/nature/rock-path-square-smal-w4tkzmjjcw 
Files: /Users/christopherneale/projects/models/nature/Rock Path Square Smal-w4TKZMjjcw.glb [847.88KB] > /Users/christopherneale/projects/fps/src/assets/nature/Rock Path Square Smal-w4TKZMjjcw-transformed.glb [52.98KB] (94%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/rock-path-square-small-variant-2-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.RockPath_Square_Small_2.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/rock-path-square-small-variant-2-transformed.glb')
