/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Rock Path Round Small.glb --transform --name RockPathRoundSmall -o /Users/christopherneale/projects/fps/src/assets/nature/rock-path-round-small 
Files: /Users/christopherneale/projects/models/nature/Rock Path Round Small.glb [876.84KB] > /Users/christopherneale/projects/fps/src/assets/nature/Rock Path Round Small-transformed.glb [55.5KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Rock Path Round Small-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.RockPath_Round_Small_3.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/Rock Path Round Small-transformed.glb')
