/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Rock Path Round Small-GMttpOEFKT.glb --transform --name RockPathRoundSmallGMttpOEFKT -o /Users/christopherneale/projects/fps/src/assets/nature/rock-path-round-small-gmttpoefkt 
Files: /Users/christopherneale/projects/models/nature/Rock Path Round Small-GMttpOEFKT.glb [885.13KB] > /Users/christopherneale/projects/fps/src/assets/nature/Rock Path Round Small-GMttpOEFKT-transformed.glb [56.22KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rock-path-round-small-variant-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.RockPath_Round_Small_2.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/rock-path-round-small-variant-1-transformed.glb')
