/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Rock Path Square Wide.glb --transform --name RockPathSquareWide -o /Users/christopherneale/projects/fps/src/assets/nature/rock-path-square-wide 
Files: /Users/christopherneale/projects/models/nature/Rock Path Square Wide.glb [963.3KB] > /Users/christopherneale/projects/fps/src/assets/nature/Rock Path Square Wide-transformed.glb [64KB] (93%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/rock-path-square-wide-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.RockPath_Square_Wide.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/rock-path-square-wide-transformed.glb')
