/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Rock Path Square Smal-cI9XBpVijV.glb --transform --name RockPathSquareSmalCI9XBpVijV -o /Users/christopherneale/projects/fps/src/assets/nature/rock-path-square-smal-ci9xbpvijv 
Files: /Users/christopherneale/projects/models/nature/Rock Path Square Smal-cI9XBpVijV.glb [862.73KB] > /Users/christopherneale/projects/fps/src/assets/nature/Rock Path Square Smal-cI9XBpVijV-transformed.glb [54.48KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Rock Path Square Smal-cI9XBpVijV-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.RockPath_Square_Small_1.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/Rock Path Square Smal-cI9XBpVijV-transformed.glb')
