/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Rock Path Round Wide.glb --transform --name RockPathRoundWide -o /Users/christopherneale/projects/fps/src/assets/nature/rock-path-round-wide 
Files: /Users/christopherneale/projects/models/nature/Rock Path Round Wide.glb [1.04MB] > /Users/christopherneale/projects/fps/src/assets/nature/Rock Path Round Wide-transformed.glb [70.67KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Rock Path Round Wide-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.RockPath_Round_Wide.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/Rock Path Round Wide-transformed.glb')
