/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Rock Path Square Smal-w4TKZMjjcw.glb --transform --name RockPathSquareSmalW4TKZMjjcw -o /Users/christopherneale/projects/fps/src/assets/nature/rock-path-square-smal-w4tkzmjjcw 
Files: /Users/christopherneale/projects/models/nature/Rock Path Square Smal-w4TKZMjjcw.glb [847.88KB] > /Users/christopherneale/projects/fps/src/assets/nature/Rock Path Square Smal-w4TKZMjjcw-transformed.glb [52.98KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Rock Path Square Smal-w4TKZMjjcw-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.RockPath_Square_Small_2.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/Rock Path Square Smal-w4TKZMjjcw-transformed.glb')
