/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Rock Medium-s1OJ3bBzqc.glb --transform --name RockMediumS1OJ3bBzqc -o /Users/christopherneale/projects/fps/src/assets/nature/rock-medium-s1oj3bbzqc 
Files: /Users/christopherneale/projects/models/nature/Rock Medium-s1OJ3bBzqc.glb [1.06MB] > /Users/christopherneale/projects/fps/src/assets/nature/Rock Medium-s1OJ3bBzqc-transformed.glb [55.72KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Rock Medium-s1OJ3bBzqc-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock_Medium_1.geometry} material={materials.Rocks} />
    </group>
  )
}

useGLTF.preload('/Rock Medium-s1OJ3bBzqc-transformed.glb')
