/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Rock Path Square Thin.glb --transform --name RockPathSquareThin -o /Users/christopherneale/projects/fps/src/assets/nature/rock-path-square-thin 
Files: /Users/christopherneale/projects/models/nature/Rock Path Square Thin.glb [931.56KB] > /Users/christopherneale/projects/fps/src/assets/nature/Rock Path Square Thin-transformed.glb [60.91KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Rock Path Square Thin-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.RockPath_Square_Thin.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/Rock Path Square Thin-transformed.glb')
