/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Rock Path Round Small-yHEdadj5I0.glb --transform --name RockPathRoundSmallYHEdadj5I0 -o /Users/christopherneale/projects/fps/src/assets/nature/rock-path-round-small-yhedadj5i0 
Files: /Users/christopherneale/projects/models/nature/Rock Path Round Small-yHEdadj5I0.glb [876.94KB] > /Users/christopherneale/projects/fps/src/assets/nature/Rock Path Round Small-yHEdadj5I0-transformed.glb [55.48KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rock-path-round-small-variant-2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.RockPath_Round_Small_1.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/rock-path-round-small-variant-2-transformed.glb')
