/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Tall Grass.glb --transform --name TallGrass -o /Users/christopherneale/projects/fps/src/assets/nature/tall-grass 
Files: /Users/christopherneale/projects/models/nature/Tall Grass.glb [88.02KB] > /Users/christopherneale/projects/fps/src/assets/nature/Tall Grass-transformed.glb [8.13KB] (91%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/tall-grass-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Grass_Common_Tall.geometry} material={materials.Grass} />
    </group>
  )
}

useGLTF.preload('/tall-grass-transformed.glb')
