/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Tall Grass.glb --transform --name TallGrass -o /Users/christopherneale/projects/fps/src/assets/nature/tall-grass 
Files: /Users/christopherneale/projects/models/nature/Tall Grass.glb [88.02KB] > /Users/christopherneale/projects/fps/src/assets/nature/Tall Grass-transformed.glb [8.13KB] (91%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Tall Grass-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Grass_Common_Tall.geometry} material={materials.Grass} />
    </group>
  )
}

useGLTF.preload('/Tall Grass-transformed.glb')
