/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Tree-QVOop92WmG.glb --transform --name TreeQVOop92WmG -o /Users/christopherneale/projects/fps/src/assets/nature/tree-qvoop92wmg 
Files: /Users/christopherneale/projects/models/nature/Tree-QVOop92WmG.glb [2.43MB] > /Users/christopherneale/projects/fps/src/assets/nature/Tree-QVOop92WmG-transformed.glb [222.24KB] (91%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tree-variant-2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CommonTree_3_1.geometry} material={materials.Bark_NormalTree} />
      <mesh geometry={nodes.CommonTree_3_2.geometry} material={materials.Leaves_NormalTree} />
    </group>
  )
}

useGLTF.preload('/tree-variant-2-transformed.glb')
