/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Tree-t9KbsfYdXz.glb --transform --name TreeT9KbsfYdXz -o /Users/christopherneale/projects/fps/src/assets/nature/tree-t9kbsfydxz 
Files: /Users/christopherneale/projects/models/nature/Tree-t9KbsfYdXz.glb [2.39MB] > /Users/christopherneale/projects/fps/src/assets/nature/Tree-t9KbsfYdXz-transformed.glb [214.63KB] (91%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Tree-t9KbsfYdXz-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CommonTree_5_1.geometry} material={materials.Bark_NormalTree} />
      <mesh geometry={nodes.CommonTree_5_2.geometry} material={materials.Leaves_NormalTree} />
    </group>
  )
}

useGLTF.preload('/Tree-t9KbsfYdXz-transformed.glb')
