/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Tree.glb --transform --name Tree -o /Users/christopherneale/projects/fps/src/assets/nature/tree 
Files: /Users/christopherneale/projects/models/nature/Tree.glb [2.39MB] > /Users/christopherneale/projects/fps/src/assets/nature/Tree-transformed.glb [211.02KB] (91%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/tree-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CommonTree_4_1.geometry} material={materials.Bark_NormalTree} />
      <mesh geometry={nodes.CommonTree_4_2.geometry} material={materials.Leaves_NormalTree} />
    </group>
  )
}

useGLTF.preload('/tree-transformed.glb')
