/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Tree-aVOxaHRPWe.glb --transform --name TreeAVOxaHRPWe -o /Users/christopherneale/projects/fps/src/assets/nature/tree-avoxahrpwe 
Files: /Users/christopherneale/projects/models/nature/Tree-aVOxaHRPWe.glb [2.48MB] > /Users/christopherneale/projects/fps/src/assets/nature/Tree-aVOxaHRPWe-transformed.glb [224.76KB] (91%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Tree-aVOxaHRPWe-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CommonTree_2_1.geometry} material={materials.Bark_NormalTree} />
      <mesh geometry={nodes.CommonTree_2_2.geometry} material={materials.Leaves_NormalTree} />
    </group>
  )
}

useGLTF.preload('/Tree-aVOxaHRPWe-transformed.glb')
