/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Tree-qZtx0AHhcy.glb --transform --name TreeQZtx0AHhcy -o /Users/christopherneale/projects/fps/src/assets/nature/tree-qztx0ahhcy 
Files: /Users/christopherneale/projects/models/nature/Tree-qZtx0AHhcy.glb [2.54MB] > /Users/christopherneale/projects/fps/src/assets/nature/Tree-qZtx0AHhcy-transformed.glb [234.23KB] (91%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Tree-qZtx0AHhcy-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CommonTree_1_1.geometry} material={materials.Bark_NormalTree} />
      <mesh geometry={nodes.CommonTree_1_2.geometry} material={materials.Leaves_NormalTree} />
    </group>
  )
}

useGLTF.preload('/Tree-qZtx0AHhcy-transformed.glb')
