/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Twisted Tree-8oraKn9m0x.glb --transform --name TwistedTree8oraKn9m0x -o /Users/christopherneale/projects/fps/src/assets/nature/twisted-tree-8orakn9m0x 
Files: /Users/christopherneale/projects/models/nature/Twisted Tree-8oraKn9m0x.glb [3.09MB] > /Users/christopherneale/projects/fps/src/assets/nature/Twisted Tree-8oraKn9m0x-transformed.glb [253.44KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/twisted-tree-variant-2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TwistedTree_3_1.geometry} material={materials.Bark_TwistedTree} />
      <mesh geometry={nodes.TwistedTree_3_2.geometry} material={materials.Leaves_TwistedTree} />
    </group>
  )
}

useGLTF.preload('/twisted-tree-variant-2-transformed.glb')
