/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Twisted Tree-7PDBpElkQr.glb --transform --name TwistedTree7PDBpElkQr -o /Users/christopherneale/projects/fps/src/assets/nature/twisted-tree-7pdbpelkqr 
Files: /Users/christopherneale/projects/models/nature/Twisted Tree-7PDBpElkQr.glb [3.08MB] > /Users/christopherneale/projects/fps/src/assets/nature/Twisted Tree-7PDBpElkQr-transformed.glb [250.95KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/twisted-tree-variant-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TwistedTree_4_1.geometry} material={materials.Bark_TwistedTree} />
      <mesh geometry={nodes.TwistedTree_4_2.geometry} material={materials.Leaves_TwistedTree} />
    </group>
  )
}

useGLTF.preload('/twisted-tree-variant-1-transformed.glb')
