/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Twisted Tree-9aWlx82xUf.glb --transform --name TwistedTree9aWlx82xUf -o /Users/christopherneale/projects/fps/src/assets/nature/twisted-tree-9awlx82xuf 
Files: /Users/christopherneale/projects/models/nature/Twisted Tree-9aWlx82xUf.glb [3.05MB] > /Users/christopherneale/projects/fps/src/assets/nature/Twisted Tree-9aWlx82xUf-transformed.glb [247.41KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Twisted Tree-9aWlx82xUf-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TwistedTree_1_1.geometry} material={materials.Bark_TwistedTree} />
      <mesh geometry={nodes.TwistedTree_1_2.geometry} material={materials.Leaves_TwistedTree} />
    </group>
  )
}

useGLTF.preload('/Twisted Tree-9aWlx82xUf-transformed.glb')
