/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Twisted Tree.glb --transform --name TwistedTree -o /Users/christopherneale/projects/fps/src/assets/nature/twisted-tree 
Files: /Users/christopherneale/projects/models/nature/Twisted Tree.glb [3.12MB] > /Users/christopherneale/projects/fps/src/assets/nature/Twisted Tree-transformed.glb [257.74KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Twisted Tree-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TwistedTree_5_1.geometry} material={materials.Bark_TwistedTree} />
      <mesh geometry={nodes.TwistedTree_5_2.geometry} material={materials.Leaves_TwistedTree} />
    </group>
  )
}

useGLTF.preload('/Twisted Tree-transformed.glb')
