/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Twisted Tree-GVTsMmuzv7.glb --transform --name TwistedTreeGVTsMmuzv7 -o /Users/christopherneale/projects/fps/src/assets/nature/twisted-tree-gvtsmmuzv7 
Files: /Users/christopherneale/projects/models/nature/Twisted Tree-GVTsMmuzv7.glb [3.03MB] > /Users/christopherneale/projects/fps/src/assets/nature/Twisted Tree-GVTsMmuzv7-transformed.glb [244.84KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Twisted Tree-GVTsMmuzv7-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TwistedTree_2_1.geometry} material={materials.Bark_TwistedTree} />
      <mesh geometry={nodes.TwistedTree_2_2.geometry} material={materials.Leaves_TwistedTree} />
    </group>
  )
}

useGLTF.preload('/Twisted Tree-GVTsMmuzv7-transformed.glb')
