/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/christopherneale/projects/models/nature/Twisted Tree-8oraKn9m0x.glb --transform --name TwistedTree8oraKn9m0x -o /Users/christopherneale/projects/fps/src/assets/nature/twisted-tree-8orakn9m0x 
Files: /Users/christopherneale/projects/models/nature/Twisted Tree-8oraKn9m0x.glb [3.09MB] > /Users/christopherneale/projects/fps/src/assets/nature/Twisted Tree-8oraKn9m0x-transformed.glb [253.44KB] (92%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Material, Mesh } from 'three'

type ModelProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, Material>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/twisted-tree-variant-2-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TwistedTree_3_1.geometry} material={materials.Bark_TwistedTree} />
      <mesh geometry={nodes.TwistedTree_3_2.geometry} material={materials.Leaves_TwistedTree} />
    </group>
  )
}

useGLTF.preload('/twisted-tree-variant-2-transformed.glb')
