/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../models/Assault Rifle.glb --transform -E -s -o ./src/assets/rifle 
Files: ../models/Assault Rifle.glb [133.98KB] > /Users/christopherneale/projects/fps/src/assets/Assault Rifle-transformed.glb [10.67KB] (92%)
*/

import { useGLTF } from '@react-three/drei'
import type { ComponentPropsWithoutRef } from 'react'
import type { GLTF } from 'three-stdlib'
import type { Mesh, MeshStandardMaterial } from 'three'

type RifleProps = ComponentPropsWithoutRef<'group'>

type GLTFResult = GLTF & {
  nodes: {
    AssaultRifle2_1_1: Mesh
    AssaultRifle2_1_2: Mesh
    AssaultRifle2_1_3: Mesh
  }
  materials: {
    Main: MeshStandardMaterial
    MainDark: MeshStandardMaterial
    MainLight: MeshStandardMaterial
  }
}

/**
 * Lightweight assault rifle mesh with baked materials for weapon pickups.
 */
export default function Rifle(props: RifleProps) {
  const { nodes, materials } = useGLTF('/AssaultRifle.glb') as unknown as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={20}>
        <mesh castShadow receiveShadow geometry={nodes.AssaultRifle2_1_1.geometry} material={materials.Main} />
        <mesh castShadow receiveShadow geometry={nodes.AssaultRifle2_1_2.geometry} material={materials.MainDark} />
        <mesh castShadow receiveShadow geometry={nodes.AssaultRifle2_1_3.geometry} material={materials.MainLight} />
      </group>
    </group>
  )
}

useGLTF.preload('/AssaultRifle.glb')
